apiVersion: demo.argoproj.io/v1alpha1
kind: RegionalTrafficRouter
metadata:
  name: demo-app-traffic
  namespace: default
spec:
  serviceName: demo-app
  regions:
  - name: secondary
    weight: 0
  - name: primary
    weight: 100